// packages/renderer-solid/src/types.ts
import type {
  AspectRatio,
  CalloutKind,
  CollectionImage,
} from "@standard-reader/renderer-core";
import type { JSX } from "solid-js";

/** Anything Solid can render in a child position. */
export type Renderable = JSX.Element;

/** A rendered table cell. */
export interface SolidTableCell {
  header: boolean;
  content: Renderable;
}

export type SolidTableRow = Array<SolidTableCell>;

// ---------------------------------------------------------------------------
// Inline (facet) components — shared
// ---------------------------------------------------------------------------

export interface SolidInlineComponents {
  /** Top-level renderer for a run of faceted plaintext. Override to take full
   *  control; otherwise it composes the marks below. */
  facetText: (
    props: { plaintext: string; facets?: Array<unknown> },
    ctx: RenderContext,
  ) => Renderable;
  strong: (children: Renderable) => Renderable;
  emphasis: (children: Renderable) => Renderable;
  inlineCode: (children: Renderable) => Renderable;
  underline: (children: Renderable) => Renderable;
  strikethrough: (children: Renderable) => Renderable;
  highlight: (children: Renderable) => Renderable;
  link: (props: { href: string }, children: Renderable) => Renderable;
  mention: (
    props: { atUri?: string; did?: string },
    children: Renderable,
  ) => Renderable;
  footnoteReference: (props: {
    footnoteId: string;
    number: number | null;
    contentPlaintext?: string;
  }) => Renderable;
}

// ---------------------------------------------------------------------------
// Block components — shared
// ---------------------------------------------------------------------------

export interface SolidSharedComponents extends SolidInlineComponents {
  root: (children: Renderable) => Renderable;
  paragraph: (props: { dropCap: boolean }, children: Renderable) => Renderable;
  heading: (props: { level: number }, children: Renderable) => Renderable;
  blockquote: (children: Renderable) => Renderable;
  callout: (
    props: {
      emoji?: string;
      color?: string;
      /** Normalized visual family for a `[!TYPE]` callout. */
      kind?: CalloutKind;
      title?: string;
      fold?: "open" | "closed";
    },
    children: Renderable,
  ) => Renderable;
  horizontalRule: () => Renderable;
  bulletList: (children: Renderable) => Renderable;
  orderedList: (props: { start?: number }, children: Renderable) => Renderable;
  listItem: (children: Renderable) => Renderable;
  taskList: (children: Renderable) => Renderable;
  taskListItem: (
    props: { checked: boolean },
    children: Renderable,
  ) => Renderable;
  code: (props: { code: string; language?: string }) => Renderable;
  /**
   * A raw HTML block from a markdown document. Renders nothing by default:
   * injecting untrusted markup is the host's decision, with the host's own
   * sanitizer. Supply this component to render it.
   */
  html: (props: { html: string }) => Renderable;
  /**
   * A self-contained HTML embed (Leaflet's `pub.leaflet.blocks.html`). Unlike
   * `html`, this one renders by default, inside a sandboxed `srcdoc` iframe as
   * the format specifies. If you override it, keep the sandbox and keep
   * `allow-same-origin` out of it — with `srcdoc` that grants the embed your
   * own origin.
   */
  htmlEmbed: (props: {
    html: string;
    height?: number;
    aspectRatio?: { width?: number; height?: number };
  }) => Renderable;
  image: (props: {
    src: string;
    alt: string;
    aspectRatio?: AspectRatio;
    fullBleed?: boolean;
    caption?: string;
  }) => Renderable;
  iframe: (props: {
    url: string;
    height?: number;
    aspectRatio?: { width?: number; height?: number };
  }) => Renderable;
  website: (props: {
    src: string;
    title?: string;
    description?: string;
    previewImage?: string;
  }) => Renderable;
  table: (props: { rows: Array<SolidTableRow> }) => Renderable;
  math: (props: { tex: string }) => Renderable;
  button: (props: {
    text: string;
    href: string;
    caption?: string;
    alignment?: string;
  }) => Renderable;
  blueskyEmbed: (props: { postUri: string }) => Renderable;
  imageGrid: (props: {
    images: Array<CollectionImage>;
    caption?: string;
    layout?: string;
  }) => Renderable;
  imageCarousel: (props: {
    images: Array<CollectionImage>;
    caption?: string;
    layout?: string;
  }) => Renderable;
  imageDiff: (props: {
    before: CollectionImage;
    after: CollectionImage;
    caption?: string;
    labels?: [string?, string?];
  }) => Renderable;
  footnotes: (children: Renderable) => Renderable;
  footnoteItem: (
    props: { id: string; number: number },
    children: Renderable,
  ) => Renderable;
  unknown: (props: { blockType: string }) => Renderable;
}

// ---------------------------------------------------------------------------
// Platform components
// ---------------------------------------------------------------------------

export interface SolidLeafletComponents {
  poll: (props: { pollUri: string }) => Renderable;
  signup: () => Renderable;
  separator: () => Renderable;
  standardSitePost: (props: { uri: string }) => Renderable;
  standardSitePublication: (props: {
    uri: string;
    cid?: string;
    showPublicationTheme?: boolean;
  }) => Renderable;
  pageEmbed: (
    props: { pageId: string; pageType?: string },
    children: Renderable,
  ) => Renderable;
}

export interface SolidPcktComponents {
  gallery: (props: { ref: string }) => Renderable;
  noteEmbed: (props: { uri?: string; cid?: string }) => Renderable;
}

export interface SolidOffprintComponents {
  component: (props: { componentUri: string }) => Renderable;
}

/** The fully-resolved component registry used internally after merging. */
export interface SolidComponents {
  shared: SolidSharedComponents;
  leaflet: SolidLeafletComponents;
  pckt: SolidPcktComponents;
  offprint: SolidOffprintComponents;
}

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? Partial<T[K]> : T[K];
};

/** The `components` input shape: override any subset. */
export type SolidComponentsInput = DeepPartial<SolidComponents>;

/** Threaded through the walk so components can render inline/child content. */
export interface RenderContext {
  components: SolidComponents;
  footnoteNumbers: ReadonlyMap<string, number>;
}

// packages/renderer-react/src/components/types.ts
import type { CalloutKind } from "@standard-reader/renderer-core";
import type { ComponentType, ReactNode } from "react";

import type { AspectRatio, TableRow } from "../types";

/**
 * Components come in two categories:
 *
 * - **Shared** components render the block and inline vocabulary that every
 *   content format has in common (paragraphs, headings, images, code, lists,
 *   inline marks, …). Override these once and they apply across Leaflet, pckt,
 *   Offprint and every third-party format.
 * - **Platform** components render the blocks unique to a single publishing
 *   platform (a Leaflet poll, a pckt gallery, an Offprint component, …). These
 *   are the interactive, often data-backed embeds; the headless defaults render
 *   inert placeholders, so supply your own to make them live.
 */

// ---------------------------------------------------------------------------
// Inline (facet) components — shared
// ---------------------------------------------------------------------------

export interface MentionProps {
  /** AT-URI target of an `atMention` (e.g. a publication or document record). */
  atUri?: string;
  /** DID target of a `didMention`. */
  did?: string;
  /** The mention's display text. */
  children: ReactNode;
}

export interface FacetLinkProps {
  href: string;
  children: ReactNode;
}

export interface FootnoteReferenceProps {
  /** Stable id shared by the inline reference and the endnote entry. */
  footnoteId: string;
  /** 1-based display number, or `null` when the note has no registered entry. */
  number: number | null;
  /** The footnote body as plaintext, for a hover preview. */
  contentPlaintext?: string;
}

export interface MarkProps {
  children: ReactNode;
}

export interface FacetTextProps {
  plaintext: string;
  /** Raw AT-Proto facets (byte-indexed), in any supported format's dialect. */
  facets?: Array<unknown>;
}

/** The inline components applied to spans of rich text. */
export interface InlineComponents {
  /** Top-level renderer for a run of faceted plaintext. Override this to take
   *  full control of inline formatting; otherwise it composes the marks below. */
  FacetText: ComponentType<FacetTextProps>;
  Strong: ComponentType<MarkProps>;
  Emphasis: ComponentType<MarkProps>;
  InlineCode: ComponentType<MarkProps>;
  Underline: ComponentType<MarkProps>;
  Strikethrough: ComponentType<MarkProps>;
  Highlight: ComponentType<MarkProps>;
  Link: ComponentType<FacetLinkProps>;
  Mention: ComponentType<MentionProps>;
  FootnoteReference: ComponentType<FootnoteReferenceProps>;
}

// ---------------------------------------------------------------------------
// Block components — shared
// ---------------------------------------------------------------------------

export interface RootProps {
  children: ReactNode;
}

export interface ParagraphProps {
  children: ReactNode;
  /** True for the body's first paragraph when drop caps are enabled. */
  dropCap?: boolean;
}

export interface HeadingProps {
  /** 1–6. */
  level: number;
  children: ReactNode;
}

export interface BlockquoteProps {
  /** One rendered paragraph per quoted line. */
  children: ReactNode;
}

export interface CalloutProps {
  emoji?: string;
  color?: string;
  /** Normalized visual family for a `[!TYPE]` callout. */
  kind?: CalloutKind;
  /** Author-supplied title from the marker line. */
  title?: string;
  /** Set only when the callout was marked collapsible. */
  fold?: "open" | "closed";
  children: ReactNode;
}

export interface HtmlProps {
  html: string;
}

export interface HtmlEmbedProps {
  html: string;
  height?: number;
  aspectRatio?: { width?: number; height?: number };
}

export interface ListProps {
  children: ReactNode;
}

export interface OrderedListProps {
  start?: number;
  children: ReactNode;
}

export interface ListItemProps {
  children: ReactNode;
}

export interface TaskListItemProps {
  checked?: boolean;
  children: ReactNode;
}

export interface CodeProps {
  code: string;
  language?: string;
}

export interface ImageProps {
  src: string;
  alt: string;
  aspectRatio?: AspectRatio;
  /** Leaflet full-bleed images request edge-to-edge layout. */
  fullBleed?: boolean;
  /** Optional caption (defaults to the alt text where the platform uses it). */
  caption?: string;
}

export interface IframeProps {
  url: string;
  height?: number;
  aspectRatio?: { width?: number; height?: number };
}

export interface WebsiteProps {
  src: string;
  title?: string;
  description?: string;
  previewImage?: string;
}

export interface TableProps {
  rows: Array<TableRow>;
}

export interface MathProps {
  tex: string;
}

export interface ButtonProps {
  text: string;
  href: string;
  caption?: string;
  alignment?: string;
}

export interface BlueskyEmbedProps {
  postUri: string;
}

export interface ImageCollectionImage {
  src: string;
  alt: string;
  aspectRatio?: AspectRatio;
}

export interface ImageCollectionProps {
  images: Array<ImageCollectionImage>;
  caption?: string;
  /** "grid" | "carousel" — the layout the source requested. */
  layout?: string;
}

export interface ImageDiffProps {
  before: ImageCollectionImage;
  after: ImageCollectionImage;
  caption?: string;
  labels?: [string?, string?];
}

export interface FootnotesProps {
  children: ReactNode;
}

export interface FootnoteItemProps {
  id: string;
  number: number;
  children: ReactNode;
}

export interface UnknownBlockProps {
  blockType: string;
}

/** The block components shared by every content format. */
export interface SharedBlockComponents {
  /** Wraps the whole rendered body. */
  Root: ComponentType<RootProps>;
  Paragraph: ComponentType<ParagraphProps>;
  Heading: ComponentType<HeadingProps>;
  Blockquote: ComponentType<BlockquoteProps>;
  Callout: ComponentType<CalloutProps>;
  /**
   * A raw HTML block from a markdown document. Renders nothing by default:
   * injecting untrusted markup is the host's decision, with the host's own
   * sanitizer. Supply this component to render it.
   */
  Html: ComponentType<HtmlProps>;
  /**
   * A self-contained HTML embed (Leaflet's `pub.leaflet.blocks.html`). Unlike
   * `Html`, this one renders by default, inside a sandboxed `srcdoc` iframe as
   * the format specifies. If you override it, keep the sandbox and keep
   * `allow-same-origin` out of it — with `srcdoc` that grants the embed your
   * own origin.
   */
  HtmlEmbed: ComponentType<HtmlEmbedProps>;
  HorizontalRule: ComponentType<Record<string, never>>;
  BulletList: ComponentType<ListProps>;
  OrderedList: ComponentType<OrderedListProps>;
  ListItem: ComponentType<ListItemProps>;
  TaskList: ComponentType<ListProps>;
  TaskListItem: ComponentType<TaskListItemProps>;
  Code: ComponentType<CodeProps>;
  Image: ComponentType<ImageProps>;
  Iframe: ComponentType<IframeProps>;
  Website: ComponentType<WebsiteProps>;
  Table: ComponentType<TableProps>;
  Math: ComponentType<MathProps>;
  Button: ComponentType<ButtonProps>;
  BlueskyEmbed: ComponentType<BlueskyEmbedProps>;
  ImageGrid: ComponentType<ImageCollectionProps>;
  ImageCarousel: ComponentType<ImageCollectionProps>;
  ImageDiff: ComponentType<ImageDiffProps>;
  Footnotes: ComponentType<FootnotesProps>;
  FootnoteItem: ComponentType<FootnoteItemProps>;
  Unknown: ComponentType<UnknownBlockProps>;
}

export type SharedComponents = SharedBlockComponents & InlineComponents;

// ---------------------------------------------------------------------------
// Platform components
// ---------------------------------------------------------------------------

export interface LeafletPollProps {
  /** AT-URI of the poll record. */
  pollUri: string;
}

export interface LeafletStandardSitePostProps {
  /** AT-URI of the embedded `site.standard.document`. */
  uri: string;
}

export interface LeafletStandardSitePublicationProps {
  /** AT-URI of the embedded `site.standard.publication`. */
  uri: string;
  cid?: string;
  showPublicationTheme?: boolean;
}

export interface LeafletPageEmbedProps {
  pageId: string;
  pageType?: string;
  /** The embedded page's rendered blocks. */
  children: ReactNode;
}

export interface LeafletComponents {
  Poll: ComponentType<LeafletPollProps>;
  Signup: ComponentType<Record<string, never>>;
  Separator: ComponentType<Record<string, never>>;
  StandardSitePost: ComponentType<LeafletStandardSitePostProps>;
  StandardSitePublication: ComponentType<LeafletStandardSitePublicationProps>;
  PageEmbed: ComponentType<LeafletPageEmbedProps>;
}

export interface PcktGalleryProps {
  /** AT-URI of the gallery blob record. */
  ref: string;
}

export interface PcktNoteEmbedProps {
  /** AT-URI of the embedded `blog.pckt.mini.post`. */
  uri?: string;
  cid?: string;
}

export interface PcktComponents {
  Gallery: ComponentType<PcktGalleryProps>;
  NoteEmbed: ComponentType<PcktNoteEmbedProps>;
}

export interface OffprintComponentProps {
  /** AT-URI of the `app.offprint.component` record to resolve on read. */
  componentUri: string;
}

export interface OffprintComponents {
  Component: ComponentType<OffprintComponentProps>;
}

// ---------------------------------------------------------------------------
// Aggregate registry
// ---------------------------------------------------------------------------

/** The fully-resolved component registry used internally after merging. */
export interface RendererComponents {
  shared: SharedComponents;
  leaflet: LeafletComponents;
  pckt: PcktComponents;
  offprint: OffprintComponents;
}

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? Partial<T[K]> : T[K];
};

/**
 * The `components` prop shape: override any subset of components; everything
 * else falls back to the unstyled defaults.
 */
export type RendererComponentsInput = DeepPartial<RendererComponents>;
