// packages/renderer-solid/src/inline.ts
import type { InlineNode, MarkKind } from "@standard-reader/renderer-core";
import h from "solid-js/h";

import type { Renderable, RenderContext, SolidSharedComponents } from "./types";

function markRenderer(
  shared: SolidSharedComponents,
  mark: MarkKind,
): (children: Renderable) => Renderable {
  switch (mark) {
    case "strong": {
      return shared.strong;
    }
    case "emphasis": {
      return shared.emphasis;
    }
    case "code": {
      return shared.inlineCode;
    }
    case "underline": {
      return shared.underline;
    }
    case "strikethrough": {
      return shared.strikethrough;
    }
    case "highlight": {
      return shared.highlight;
    }
  }
}

/** Render a list of {@link InlineNode}s to Solid children. */
export function renderInlineNodes(
  nodes: Array<InlineNode>,
  ctx: RenderContext,
): Array<Renderable> {
  return nodes.map((node) => renderInline(node, ctx));
}

function renderInline(node: InlineNode, ctx: RenderContext): Renderable {
  const shared = ctx.components.shared;
  switch (node.type) {
    case "text": {
      return node.value;
    }
    case "lineBreak": {
      // `solid-js/h` returns a thunk that Solid renders fine but which its
      // `JSX.Element` type doesn't cover — the same cast `defaults.ts` makes.
      return h("br") as unknown as Renderable;
    }
    case "mark": {
      return markRenderer(
        shared,
        node.mark,
      )(renderInlineNodes(node.children, ctx));
    }
    case "link": {
      return shared.link(
        { href: node.href },
        renderInlineNodes(node.children, ctx),
      );
    }
    case "mention": {
      return shared.mention(
        { atUri: node.atUri, did: node.did },
        renderInlineNodes(node.children, ctx),
      );
    }
    case "footnoteRef": {
      return shared.footnoteReference({
        footnoteId: node.footnoteId,
        number: node.number,
        contentPlaintext: node.contentPlaintext,
      });
    }
  }
}

// packages/renderer-lit/src/inline.ts
import type { InlineNode, MarkKind } from "@standard-reader/renderer-core";
import { html } from "lit";

import type { LitSharedComponents, Renderable, RenderContext } from "./types";

function markRenderer(
  shared: LitSharedComponents,
  mark: MarkKind,
): (children: Renderable) => Renderable {
  switch (mark) {
    case "strong": {
      return shared.strong;
    }
    case "emphasis": {
      return shared.emphasis;
    }
    case "code": {
      return shared.inlineCode;
    }
    case "underline": {
      return shared.underline;
    }
    case "strikethrough": {
      return shared.strikethrough;
    }
    case "highlight": {
      return shared.highlight;
    }
  }
}

/** Render a list of {@link InlineNode}s to a lit-renderable value. */
export function renderInlineNodes(
  nodes: Array<InlineNode>,
  ctx: RenderContext,
): Renderable {
  return nodes.map((node) => renderInline(node, ctx));
}

function renderInline(node: InlineNode, ctx: RenderContext): Renderable {
  const shared = ctx.components.shared;
  switch (node.type) {
    case "text": {
      return node.value;
    }
    case "lineBreak": {
      return html`<br />`;
    }
    case "mark": {
      return markRenderer(
        shared,
        node.mark,
      )(renderInlineNodes(node.children, ctx));
    }
    case "link": {
      return shared.link(
        { href: node.href },
        renderInlineNodes(node.children, ctx),
      );
    }
    case "mention": {
      return shared.mention(
        { atUri: node.atUri, did: node.did },
        renderInlineNodes(node.children, ctx),
      );
    }
    case "footnoteRef": {
      return shared.footnoteReference({
        footnoteId: node.footnoteId,
        number: node.number,
        contentPlaintext: node.contentPlaintext,
      });
    }
  }
}
