// packages/renderer-solid/src/types.ts
import type {
  AspectRatio,
  CalloutKind,
  CollectionImage,
} from "@standard-reader/renderer-core";
import type { JSX } from "solid-js";

/** Anything Solid can render in a child position. */
export type Renderable = JSX.Element;

/** A rendered table cell. */
export interface SolidTableCell {
  header: boolean;
  content: Renderable;
}

export type SolidTableRow = Array<SolidTableCell>;

// ---------------------------------------------------------------------------
// Inline (facet) components — shared
// ---------------------------------------------------------------------------

export interface SolidInlineComponents {
  /** Top-level renderer for a run of faceted plaintext. Override to take full
   *  control; otherwise it composes the marks below. */
  facetText: (
    props: { plaintext: string; facets?: Array<unknown> },
    ctx: RenderContext,
  ) => Renderable;
  strong: (children: Renderable) => Renderable;
  emphasis: (children: Renderable) => Renderable;
  inlineCode: (children: Renderable) => Renderable;
  underline: (children: Renderable) => Renderable;
  strikethrough: (children: Renderable) => Renderable;
  highlight: (children: Renderable) => Renderable;
  link: (props: { href: string }, children: Renderable) => Renderable;
  mention: (
    props: { atUri?: string; did?: string },
    children: Renderable,
  ) => Renderable;
  footnoteReference: (props: {
    footnoteId: string;
    number: number | null;
    contentPlaintext?: string;
  }) => Renderable;
}

// ---------------------------------------------------------------------------
// Block components — shared
// ---------------------------------------------------------------------------

export interface SolidSharedComponents extends SolidInlineComponents {
  root: (children: Renderable) => Renderable;
  paragraph: (props: { dropCap: boolean }, children: Renderable) => Renderable;
  heading: (props: { level: number }, children: Renderable) => Renderable;
  blockquote: (children: Renderable) => Renderable;
  callout: (
    props: {
      emoji?: string;
      color?: string;
      /** Normalized visual family for a `[!TYPE]` callout. */
      kind?: CalloutKind;
      title?: string;
      fold?: "open" | "closed";
    },
    children: Renderable,
  ) => Renderable;
  horizontalRule: () => Renderable;
  bulletList: (children: Renderable) => Renderable;
  orderedList: (props: { start?: number }, children: Renderable) => Renderable;
  listItem: (children: Renderable) => Renderable;
  taskList: (children: Renderable) => Renderable;
  taskListItem: (
    props: { checked: boolean },
    children: Renderable,
  ) => Renderable;
  code: (props: { code: string; language?: string }) => Renderable;
  /**
   * A raw HTML block from a markdown document. Renders nothing by default:
   * injecting untrusted markup is the host's decision, with the host's own
   * sanitizer. Supply this component to render it.
   */
  html: (props: { html: string }) => Renderable;
  /**
   * A self-contained HTML embed (Leaflet's `pub.leaflet.blocks.html`). Unlike
   * `html`, this one renders by default, inside a sandboxed `srcdoc` iframe as
   * the format specifies. If you override it, keep the sandbox and keep
   * `allow-same-origin` out of it — with `srcdoc` that grants the embed your
   * own origin.
   */
  htmlEmbed: (props: {
    html: string;
    height?: number;
    aspectRatio?: { width?: number; height?: number };
  }) => Renderable;
  image: (props: {
    src: string;
    alt: string;
    aspectRatio?: AspectRatio;
    fullBleed?: boolean;
    caption?: string;
  }) => Renderable;
  iframe: (props: {
    url: string;
    height?: number;
    aspectRatio?: { width?: number; height?: number };
  }) => Renderable;
  website: (props: {
    src: string;
    title?: string;
    description?: string;
    previewImage?: string;
  }) => Renderable;
  table: (props: { rows: Array<SolidTableRow> }) => Renderable;
  math: (props: { tex: string }) => Renderable;
  button: (props: {
    text: string;
    href: string;
    caption?: string;
    alignment?: string;
  }) => Renderable;
  blueskyEmbed: (props: { postUri: string }) => Renderable;
  imageGrid: (props: {
    images: Array<CollectionImage>;
    caption?: string;
    layout?: string;
  }) => Renderable;
  imageCarousel: (props: {
    images: Array<CollectionImage>;
    caption?: string;
    layout?: string;
  }) => Renderable;
  imageDiff: (props: {
    before: CollectionImage;
    after: CollectionImage;
    caption?: string;
    labels?: [string?, string?];
  }) => Renderable;
  footnotes: (children: Renderable) => Renderable;
  footnoteItem: (
    props: { id: string; number: number },
    children: Renderable,
  ) => Renderable;
  unknown: (props: { blockType: string }) => Renderable;
}

// ---------------------------------------------------------------------------
// Platform components
// ---------------------------------------------------------------------------

export interface SolidLeafletComponents {
  poll: (props: { pollUri: string }) => Renderable;
  signup: () => Renderable;
  separator: () => Renderable;
  standardSitePost: (props: { uri: string }) => Renderable;
  standardSitePublication: (props: {
    uri: string;
    cid?: string;
    showPublicationTheme?: boolean;
  }) => Renderable;
  pageEmbed: (
    props: { pageId: string; pageType?: string },
    children: Renderable,
  ) => Renderable;
}

export interface SolidPcktComponents {
  gallery: (props: { ref: string }) => Renderable;
  noteEmbed: (props: { uri?: string; cid?: string }) => Renderable;
}

export interface SolidOffprintComponents {
  component: (props: { componentUri: string }) => Renderable;
}

/** The fully-resolved component registry used internally after merging. */
export interface SolidComponents {
  shared: SolidSharedComponents;
  leaflet: SolidLeafletComponents;
  pckt: SolidPcktComponents;
  offprint: SolidOffprintComponents;
}

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? Partial<T[K]> : T[K];
};

/** The `components` input shape: override any subset. */
export type SolidComponentsInput = DeepPartial<SolidComponents>;

/** Threaded through the walk so components can render inline/child content. */
export interface RenderContext {
  components: SolidComponents;
  footnoteNumbers: ReadonlyMap<string, number>;
}

// packages/renderer-angular/src/types.ts
import type { TemplateRef } from "@angular/core";
import type {
  AspectRatio,
  CollectionImage,
  RichText,
} from "@standard-reader/renderer-core";

/** An override template. The node's props arrive as the `$implicit` context —
 *  bind them with `let-p` (or `let-p="$implicit"`) on your `<ng-template>`. */
export type Tpl<T> = TemplateRef<{ $implicit: T }>;

/**
 * Component overrides are Angular {@link TemplateRef}s keyed by node type. They
 * cover the media and data-backed blocks that most need customizing; structural
 * blocks (paragraphs, headings, lists, …) render as unstyled semantic HTML you
 * style with CSS.
 *
 * ```html
 * <ng-template #poll let-p><live-poll [uri]="p.pollUri" /></ng-template>
 * <sr-standard-document [document]="doc" [components]="{ leaflet: { poll } }" />
 * ```
 */
export interface AngularSharedComponents {
  image?: Tpl<{
    src: string;
    alt: string;
    aspectRatio?: AspectRatio;
    fullBleed?: boolean;
    caption?: string;
  }>;
  code?: Tpl<{ code: string; language?: string }>;
  /**
   * A raw HTML block from a markdown document. Renders nothing by default:
   * injecting untrusted markup is the host's decision, with the host's own
   * sanitizer. Supply this template to render it.
   */
  html?: Tpl<{ html: string }>;
  /**
   * A self-contained HTML embed (Leaflet's `pub.leaflet.blocks.html`). Unlike
   * `html`, this one renders by default, inside a sandboxed `srcdoc` iframe as
   * the format specifies. If you override it, keep the sandbox and keep
   * `allow-same-origin` out of it — with `srcdoc` that grants the embed your
   * own origin.
   */
  htmlEmbed?: Tpl<{
    html: string;
    height?: number;
    aspectRatio?: { width?: number; height?: number };
  }>;
  iframe?: Tpl<{
    url: string;
    height?: number;
    aspectRatio?: { width?: number; height?: number };
  }>;
  website?: Tpl<{
    src: string;
    title?: string;
    description?: string;
    previewImage?: string;
  }>;
  table?: Tpl<{ rows: Array<Array<{ header: boolean; text: RichText }>> }>;
  math?: Tpl<{ tex: string }>;
  button?: Tpl<{
    text: string;
    href: string;
    caption?: string;
    alignment?: string;
  }>;
  blueskyEmbed?: Tpl<{ postUri: string }>;
  imageGrid?: Tpl<{
    images: Array<CollectionImage>;
    caption?: string;
    layout?: string;
  }>;
  imageCarousel?: Tpl<{
    images: Array<CollectionImage>;
    caption?: string;
    layout?: string;
  }>;
  imageDiff?: Tpl<{
    before: CollectionImage;
    after: CollectionImage;
    caption?: string;
    labels?: [string?, string?];
  }>;
  unknown?: Tpl<{ blockType: string }>;
}

export interface AngularLeafletComponents {
  poll?: Tpl<{ pollUri: string }>;
  signup?: Tpl<Record<string, never>>;
  separator?: Tpl<Record<string, never>>;
  standardSitePost?: Tpl<{ uri: string }>;
  standardSitePublication?: Tpl<{
    uri: string;
    cid?: string;
    showPublicationTheme?: boolean;
  }>;
}

export interface AngularPcktComponents {
  gallery?: Tpl<{ ref: string }>;
  noteEmbed?: Tpl<{ uri?: string; cid?: string }>;
}

export interface AngularOffprintComponents {
  component?: Tpl<{ componentUri: string }>;
}

/** The `components` input: override any subset with `<ng-template>` refs. */
export interface AngularComponents {
  shared?: AngularSharedComponents;
  leaflet?: AngularLeafletComponents;
  pckt?: AngularPcktComponents;
  offprint?: AngularOffprintComponents;
}
